"""
PathWise AI — Streamlit Dashboard (app.py)
"Learn Smarter. Progress Faster."

6 pages:
  1. Dashboard       — system overview + live KPIs
  2. Student Profile — per-student mastery state
  3. Knowledge Graph — interactive network viz
  4. Learning Path   — top-3 recommendations + utility breakdown
  5. RL Policy       — Q-heatmap, reward curve, convergence
  6. Analytics       — LE / MR / SS metrics + baseline comparison

Run locally:
    streamlit run app.py

Requires: q_table.pkl, students.json, metrics.json,
          training_history.json  (generated by pathwise_ai.py)
"""

import streamlit as st
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import networkx as nx
import pickle, json, os
from collections import defaultdict
from typing import Dict, List, Any

# ── Page config ──────────────────────────────────────────────────
st.set_page_config(
    page_title="PathWise AI",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Domain constants (mirror pathwise_ai.py — no retraining) ────
CONCEPTS: Dict[str, Dict] = {
    'C01': {'name': 'Python Basics',             'difficulty': 1, 'est_hours': 4,  'importance': 0.95, 'ctype': 'programming'},
    'C02': {'name': 'Statistics Fundamentals',    'difficulty': 2, 'est_hours': 6,  'importance': 0.90, 'ctype': 'theory'},
    'C03': {'name': 'Linear Algebra',             'difficulty': 2, 'est_hours': 5,  'importance': 0.85, 'ctype': 'theory'},
    'C04': {'name': 'Data Wrangling (Pandas)',    'difficulty': 2, 'est_hours': 5,  'importance': 0.88, 'ctype': 'programming'},
    'C05': {'name': 'Exploratory Data Analysis',  'difficulty': 3, 'est_hours': 6,  'importance': 0.87, 'ctype': 'practice'},
    'C06': {'name': 'Probability Theory',         'difficulty': 3, 'est_hours': 5,  'importance': 0.83, 'ctype': 'theory'},
    'C07': {'name': 'Machine Learning Basics',    'difficulty': 3, 'est_hours': 8,  'importance': 0.92, 'ctype': 'theory'},
    'C08': {'name': 'Supervised Learning',        'difficulty': 4, 'est_hours': 8,  'importance': 0.93, 'ctype': 'practice'},
    'C09': {'name': 'Unsupervised Learning',      'difficulty': 4, 'est_hours': 7,  'importance': 0.82, 'ctype': 'practice'},
    'C10': {'name': 'Feature Engineering',        'difficulty': 4, 'est_hours': 6,  'importance': 0.85, 'ctype': 'practice'},
    'C11': {'name': 'Model Evaluation',           'difficulty': 4, 'est_hours': 5,  'importance': 0.88, 'ctype': 'practice'},
    'C12': {'name': 'Deep Learning Intro',        'difficulty': 5, 'est_hours': 10, 'importance': 0.80, 'ctype': 'theory'},
    'C13': {'name': 'NLP Fundamentals',           'difficulty': 5, 'est_hours': 8,  'importance': 0.75, 'ctype': 'practice'},
    'C14': {'name': 'MLOps & Deployment',         'difficulty': 5, 'est_hours': 9,  'importance': 0.78, 'ctype': 'programming'},
    'C15': {'name': 'Capstone Project',           'difficulty': 5, 'est_hours': 12, 'importance': 1.00, 'ctype': 'practice'},
}

PREREQUISITES = [
    ('C01','C02'),('C01','C03'),('C01','C04'),
    ('C02','C05'),('C02','C06'),('C02','C07'),
    ('C03','C07'),('C03','C12'),
    ('C04','C05'),('C04','C10'),
    ('C05','C07'),('C05','C08'),
    ('C06','C07'),('C06','C09'),
    ('C07','C08'),('C07','C09'),
    ('C08','C10'),('C08','C11'),('C08','C12'),
    ('C09','C10'),('C09','C11'),
    ('C10','C11'),('C10','C13'),
    ('C11','C14'),('C12','C13'),('C13','C14'),('C14','C15'),
]

CONCEPT_IDS   = list(CONCEPTS.keys())
CONCEPT_INDEX = {cid: i for i, cid in enumerate(CONCEPT_IDS)}
N_CONCEPTS    = len(CONCEPT_IDS)

MASTERY_THRESHOLD  = 0.70
PREFERENCE_AFFINITY = {
    'visual':   {'programming': 0.65, 'theory': 0.55, 'practice': 0.80},
    'reading':  {'programming': 0.60, 'theory': 0.85, 'practice': 0.55},
    'practice': {'programming': 0.85, 'theory': 0.50, 'practice': 0.90},
}
GOAL_IMPORTANCE = {
    'speed':         {1:1.0, 2:0.85, 3:0.65, 4:0.45, 5:0.30},
    'depth':         {1:0.5, 2:0.65, 3:0.80, 4:0.85, 5:0.90},
    'certification': {1:0.7, 2:0.75, 3:0.80, 4:0.85, 5:0.90},
}
UTIL_W = {'mastery': 0.35, 'time': 0.25, 'preference': 0.20, 'goal': 0.20}

# ── Data loading ──────────────────────────────────────────────────

DATA_DIR = os.path.join(os.path.dirname(__file__), 'pathwise_output')

@st.cache_data
def load_artefacts():
    artefacts = {}
    try:
        with open(f'{DATA_DIR}/q_table.pkl', 'rb') as f:
            raw = pickle.load(f)
        # Reconstruct nested defaultdict
        q = defaultdict(lambda: defaultdict(float))
        for k, v in raw.items():
            q[k].update(v)
        artefacts['q_table'] = q
    except FileNotFoundError:
        artefacts['q_table'] = defaultdict(lambda: defaultdict(float))

    try:
        with open(f'{DATA_DIR}/students.json') as f:
            artefacts['students'] = json.load(f)
    except FileNotFoundError:
        artefacts['students'] = []

    try:
        with open(f'{DATA_DIR}/metrics.json') as f:
            artefacts['metrics'] = json.load(f)
    except FileNotFoundError:
        artefacts['metrics'] = {}

    try:
        with open(f'{DATA_DIR}/training_history.json') as f:
            artefacts['history'] = json.load(f)
    except FileNotFoundError:
        artefacts['history'] = {}

    return artefacts

# ── Helper functions ──────────────────────────────────────────────

def build_kg() -> nx.DiGraph:
    G = nx.DiGraph()
    for cid, attrs in CONCEPTS.items():
        G.add_node(cid, **attrs)
    for s, d in PREREQUISITES:
        G.add_edge(s, d)
    return G

def prerequisites_satisfied(cid: str, mastery: List[float]) -> bool:
    G = build_kg()
    for p in G.predecessors(cid):
        if mastery[CONCEPT_INDEX[p]] < MASTERY_THRESHOLD:
            return False
    return True

def get_valid_actions(mastery: List[float]) -> List[str]:
    valid = [cid for cid in CONCEPT_IDS
             if mastery[CONCEPT_INDEX[cid]] < 1.0
             and prerequisites_satisfied(cid, mastery)]
    return valid or [CONCEPT_IDS[0]]

def compute_utility(cid: str, student: Dict) -> float:
    mastery   = student['mastery_vector']
    pref      = student['learning_preference']
    goal      = student['learning_goal']
    avail_h   = student['available_hours']
    ctype     = CONCEPTS[cid]['ctype']
    diff      = CONCEPTS[cid]['difficulty']
    est_h     = CONCEPTS[cid]['est_hours']

    u_m = 0.5  # simplified: replace with BN inference if available
    u_t = float(np.clip(1.0 - max(0.0, est_h - avail_h*2) / (est_h + 1e-9), 0, 1))
    u_p = PREFERENCE_AFFINITY[pref][ctype]
    u_g = float(np.clip(GOAL_IMPORTANCE[goal][diff] + CONCEPTS[cid]['importance']*0.15, 0, 1))
    return (UTIL_W['mastery']*u_m + UTIL_W['time']*u_t +
            UTIL_W['preference']*u_p + UTIL_W['goal']*u_g)

def recommend_top3(student: Dict, q_table) -> List[Dict]:
    mastery = student['mastery_vector']
    G       = build_kg()
    valid   = get_valid_actions(mastery)

    def encode_state(s_dict):
        bins = CONFIG_BINS = [0.0, 0.33, 0.70, 1.01]
        m_bins = tuple(int(np.digitize(m, bins) - 1) for m in s_dict['mastery_vector'])
        hbin   = int(np.digitize(s_dict['available_hours'], [0,4,6,9]) - 1)
        genc   = ['speed','depth','certification'].index(s_dict['learning_goal'])
        return hash(m_bins + (hbin, genc))

    state  = encode_state(student)
    scored = []
    for cid in valid:
        q_val  = q_table[state].get(cid, 0.0) if state in q_table else 0.0
        util   = compute_utility(cid, student)
        scored.append({
            'concept_id':    cid,
            'concept_name':  CONCEPTS[cid]['name'],
            'q_value':       round(float(q_val), 4),
            'utility_score': round(util, 4),
            'difficulty':    CONCEPTS[cid]['difficulty'],
            'est_hours':     CONCEPTS[cid]['est_hours'],
            'prereq_ok':     prerequisites_satisfied(cid, mastery),
        })
    scored.sort(key=lambda x: (x['q_value'], x['utility_score']), reverse=True)
    return scored[:3]

def mastery_color(m: float) -> str:
    if m < 0.33:  return '#FF6B6B'
    if m < 0.70:  return '#FFD93D'
    return '#6BCB77'

# ── Sidebar ───────────────────────────────────────────────────────

artefacts = load_artefacts()
students  = artefacts.get('students', [])
q_table   = artefacts.get('q_table', {})
metrics   = artefacts.get('metrics', {})
history   = artefacts.get('history', {})

with st.sidebar:
    st.image("https://via.placeholder.com/200x60/1f2937/ffffff?text=PathWise+AI",
             use_column_width=True)
    st.caption("Adaptive Learning System v1.0")
    st.divider()

    page = st.radio("Navigation", [
        "🏠 Dashboard",
        "👤 Student Profile",
        "🕸️ Knowledge Graph",
        "🎯 Learning Path",
        "🤖 RL Policy",
        "📊 Analytics",
    ])

    if students:
        sid_options = [s['student_id'] for s in students[:50]]
        selected_sid = st.selectbox("Select Student", sid_options)
        selected_student = next((s for s in students if s['student_id'] == selected_sid), students[0])
    else:
        selected_student = None
        selected_sid = "N/A"

    st.divider()
    st.info(f"**{len(students)}** students loaded" if students
            else "⚠️ Run pathwise_ai.py first to generate data")

# ═══════════════════════════════════════════════════════════════════
# PAGE 1 — DASHBOARD
# ═══════════════════════════════════════════════════════════════════

if page == "🏠 Dashboard":
    st.title("🧠 PathWise AI — Adaptive Learning System")
    st.caption("Data Science & ML Certification Program")
    st.divider()

    # KPI row
    c1, c2, c3, c4, c5 = st.columns(5)
    with c1:
        st.metric("Total Students", len(students))
    with c2:
        le = metrics.get('pathwise_le', 0)
        st.metric("Learning Efficiency", f"{le:.2f}%",
                  delta=f"+{metrics.get('le_improvement_pct', 0):.1f}% vs random")
    with c3:
        mr = metrics.get('avg_mastery_rate', 0)
        st.metric("Avg Mastery Rate", f"{mr:.1f}%")
    with c4:
        ss = metrics.get('avg_satisfaction', 0)
        st.metric("Avg Satisfaction", f"{ss:.3f}")
    with c5:
        conv = history.get('converged_at')
        st.metric("Q-Table Converged", f"Ep {conv}" if conv else "—")

    st.divider()
    col_left, col_right = st.columns([2, 1])

    with col_left:
        rewards = history.get('episode_rewards', [])
        if rewards:
            df_r = pd.DataFrame({'Episode': range(len(rewards)), 'Reward': rewards})
            df_r['Smoothed'] = df_r['Reward'].rolling(20, min_periods=1).mean()
            fig = go.Figure()
            fig.add_trace(go.Scatter(x=df_r['Episode'], y=df_r['Reward'],
                                     name='Raw', opacity=0.3, line=dict(color='lightcoral')))
            fig.add_trace(go.Scatter(x=df_r['Episode'], y=df_r['Smoothed'],
                                     name='Smoothed', line=dict(color='crimson', width=2)))
            fig.update_layout(title='Cumulative Reward over Training',
                              xaxis_title='Episode', yaxis_title='Episode Reward',
                              height=320, template='plotly_white')
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.warning("No training history. Run pathwise_ai.py first.")

    with col_right:
        st.subheader("System Architecture")
        st.markdown("""
| Module | Status |
|--------|--------|
| Knowledge Graph | ✅ 15 nodes |
| Bayesian Network | ✅ 5 nodes |
| MDP Environment  | ✅ Active |
| Q-Learning Agent | ✅ Trained |
| Utility Calculator | ✅ 4-attr |
| Recommendation Engine | ✅ Top-3 |
| Analytics Engine | ✅ 10 charts |
        """)

# ═══════════════════════════════════════════════════════════════════
# PAGE 2 — STUDENT PROFILE
# ═══════════════════════════════════════════════════════════════════

elif page == "👤 Student Profile":
    st.title("👤 Student Profile")
    if not selected_student:
        st.error("No student data loaded.")
        st.stop()

    s = selected_student
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Student ID",          s['student_id'])
        st.metric("Learning Goal",        s['learning_goal'].title())
    with col2:
        st.metric("Learning Preference",  s['learning_preference'].title())
        st.metric("Available Hours/Day",  f"{s['available_hours']:.1f}h")
    with col3:
        mastered = sum(1 for m in s['mastery_vector'] if m >= MASTERY_THRESHOLD)
        st.metric("Concepts Mastered",    f"{mastered}/{N_CONCEPTS}")
        st.metric("Satisfaction Score",   f"{s['satisfaction']:.3f}")

    st.divider()
    st.subheader("Mastery Vector")

    mv     = s['mastery_vector']
    labels = [f"{cid}: {CONCEPTS[cid]['name'][:20]}" for cid in CONCEPT_IDS]
    colors = [mastery_color(m) for m in mv]

    fig = go.Figure(go.Bar(
        x=labels, y=mv,
        marker_color=colors,
        text=[f"{m:.2f}" for m in mv],
        textposition='outside',
    ))
    fig.add_hline(y=MASTERY_THRESHOLD, line_dash='dash', line_color='green',
                  annotation_text=f'Mastery threshold ({MASTERY_THRESHOLD})')
    fig.update_layout(
        title=f'Mastery Vector — {s["student_id"]}',
        xaxis_title='Concept', yaxis_title='Mastery Score',
        yaxis_range=[0, 1.15], height=400, template='plotly_white',
        xaxis_tickangle=-45
    )
    st.plotly_chart(fig, use_container_width=True)

    st.divider()
    st.subheader("Prior vs Current Knowledge")
    df_compare = pd.DataFrame({
        'Concept': [CONCEPTS[cid]['name'] for cid in CONCEPT_IDS],
        'Prior':   s['prior_knowledge'],
        'Current': mv,
    })
    fig2 = go.Figure()
    fig2.add_trace(go.Bar(name='Prior',   x=df_compare['Concept'], y=df_compare['Prior'],
                          marker_color='#A8C8FF', opacity=0.8))
    fig2.add_trace(go.Bar(name='Current', x=df_compare['Concept'], y=df_compare['Current'],
                          marker_color='#4D96FF'))
    fig2.update_layout(barmode='group', height=350, template='plotly_white',
                       xaxis_tickangle=-45,
                       title='Prior Knowledge vs Current Mastery')
    st.plotly_chart(fig2, use_container_width=True)

# ═══════════════════════════════════════════════════════════════════
# PAGE 3 — KNOWLEDGE GRAPH
# ═══════════════════════════════════════════════════════════════════

elif page == "🕸️ Knowledge Graph":
    st.title("🕸️ Knowledge Graph")
    st.caption("Prerequisite dependency network for 15 Data Science concepts")

    G  = build_kg()
    mv = selected_student['mastery_vector'] if selected_student else [0.0]*N_CONCEPTS

    recs = recommend_top3(selected_student, q_table) if selected_student else []
    rec_ids = {r['concept_id'] for r in recs}

    # Build Plotly interactive graph
    level_x = {1: [], 2: [], 3: [], 4: [], 5: []}
    for cid, attrs in CONCEPTS.items():
        level_x[attrs['difficulty']].append(cid)

    pos = {}
    for lvl, nodes in level_x.items():
        for j, n in enumerate(nodes):
            pos[n] = ((j - (len(nodes)-1)/2)*2.5, -lvl*2)

    edge_x, edge_y = [], []
    for s_node, d_node in G.edges():
        x0,y0 = pos[s_node]; x1,y1 = pos[d_node]
        edge_x += [x0,x1,None]; edge_y += [y0,y1,None]

    edge_trace = go.Scatter(x=edge_x, y=edge_y, mode='lines',
                             line=dict(width=1.5, color='#888'),
                             hoverinfo='none')

    node_x = [pos[n][0] for n in CONCEPT_IDS]
    node_y = [pos[n][1] for n in CONCEPT_IDS]
    node_colors = []
    node_text   = []
    for cid in CONCEPT_IDS:
        m = mv[CONCEPT_INDEX[cid]]
        if cid in rec_ids:
            node_colors.append('#4D96FF')
        else:
            node_colors.append(mastery_color(m))
        node_text.append(
            f"<b>{cid}: {CONCEPTS[cid]['name']}</b><br>"
            f"Difficulty: {CONCEPTS[cid]['difficulty']}<br>"
            f"Est. Hours: {CONCEPTS[cid]['est_hours']}<br>"
            f"Mastery: {m:.2f}<br>"
            f"{'⭐ RECOMMENDED' if cid in rec_ids else ''}"
        )

    node_trace = go.Scatter(
        x=node_x, y=node_y, mode='markers+text',
        hoverinfo='text', hovertext=node_text,
        text=CONCEPT_IDS,
        textposition='middle center',
        marker=dict(size=38, color=node_colors,
                    line=dict(width=2, color='white')),
        textfont=dict(size=9, color='black')
    )

    fig = go.Figure(data=[edge_trace, node_trace],
                    layout=go.Layout(
                        title=f'PathWise AI — Knowledge Graph'
                              + (f' | {selected_sid}' if selected_student else ''),
                        showlegend=False,
                        hovermode='closest',
                        height=600,
                        margin=dict(b=20,l=5,r=5,t=40),
                        xaxis=dict(showgrid=False,zeroline=False,showticklabels=False),
                        yaxis=dict(showgrid=False,zeroline=False,showticklabels=False),
                        template='plotly_white'
                    ))

    legend_html = """
    <div style="display:flex;gap:20px;margin-bottom:8px">
        <span style="background:#FF6B6B;padding:2px 10px;border-radius:4px">Not Started</span>
        <span style="background:#FFD93D;padding:2px 10px;border-radius:4px">In Progress</span>
        <span style="background:#6BCB77;padding:2px 10px;border-radius:4px">Mastered</span>
        <span style="background:#4D96FF;color:white;padding:2px 10px;border-radius:4px">Recommended</span>
    </div>
    """
    st.markdown(legend_html, unsafe_allow_html=True)
    st.plotly_chart(fig, use_container_width=True)

# ═══════════════════════════════════════════════════════════════════
# PAGE 4 — LEARNING PATH
# ═══════════════════════════════════════════════════════════════════

elif page == "🎯 Learning Path":
    st.title("🎯 Personalised Learning Path")
    if not selected_student:
        st.error("No student data loaded.")
        st.stop()

    s    = selected_student
    recs = recommend_top3(s, q_table)

    st.subheader(f"Top 3 Recommendations for {s['student_id']}")
    st.caption(f"Goal: **{s['learning_goal'].title()}** | Preference: **{s['learning_preference'].title()}** | Hours/Day: **{s['available_hours']:.1f}**")

    for rank, rec in enumerate(recs, 1):
        color = ['#4D96FF','#6BCB77','#FFD93D'][rank-1]
        with st.expander(f"#{rank} — {rec['concept_id']}: {rec['concept_name']}", expanded=(rank==1)):
            c1,c2,c3,c4 = st.columns(4)
            c1.metric("Q-Value",       f"{rec['q_value']:.4f}")
            c2.metric("Utility Score", f"{rec['utility_score']:.4f}")
            c3.metric("Difficulty",    f"{rec['difficulty']}/5")
            c4.metric("Est. Hours",    f"{rec['est_hours']}h")

            # Utility breakdown
            cid  = rec['concept_id']
            u_m  = 0.50
            u_t  = float(np.clip(1.0 - max(0.0,
                          rec['est_hours'] - s['available_hours']*2) / (rec['est_hours']+1e-9), 0, 1))
            u_p  = PREFERENCE_AFFINITY[s['learning_preference']][CONCEPTS[cid]['ctype']]
            u_g  = float(np.clip(GOAL_IMPORTANCE[s['learning_goal']][rec['difficulty']] +
                          CONCEPTS[cid]['importance']*0.15, 0, 1))
            labels = ['Mastery (BN)', 'Time Fit', 'Preference', 'Goal Align']
            values = [u_m, u_t, u_p, u_g]
            weights= [UTIL_W['mastery'], UTIL_W['time'], UTIL_W['preference'], UTIL_W['goal']]
            weighted = [v*w for v,w in zip(values, weights)]

            fig = go.Figure(go.Bar(
                x=labels, y=weighted,
                marker_color=['#4D96FF','#6BCB77','#FFD93D','#FF9F45'],
                text=[f"{v:.3f}" for v in weighted], textposition='outside',
            ))
            fig.update_layout(title='Utility Component Breakdown',
                              yaxis_range=[0,0.5], height=280,
                              template='plotly_white')
            st.plotly_chart(fig, use_container_width=True)

    st.divider()
    st.subheader("Utility Sensitivity Analysis")
    valid_acts = get_valid_actions(s['mastery_vector'])
    scenarios  = ['Baseline (0.35/0.25/0.20/0.20)',
                  'Mastery Focus (0.60/0.15/0.15/0.10)',
                  'Time Focus   (0.20/0.55/0.15/0.10)',
                  'Goal Focus   (0.20/0.15/0.15/0.50)']
    scenario_weights = [
        (0.35, 0.25, 0.20, 0.20),
        (0.60, 0.15, 0.15, 0.10),
        (0.20, 0.55, 0.15, 0.10),
        (0.20, 0.15, 0.15, 0.50),
    ]
    sens_rows = []
    for label, (wm,wt,wp,wg) in zip(scenarios, scenario_weights):
        for cid in valid_acts[:8]:
            u_m2 = 0.50
            u_t2 = float(np.clip(1.0 - max(0.0, CONCEPTS[cid]['est_hours'] -
                          s['available_hours']*2) / (CONCEPTS[cid]['est_hours']+1e-9), 0, 1))
            u_p2 = PREFERENCE_AFFINITY[s['learning_preference']][CONCEPTS[cid]['ctype']]
            u_g2 = float(np.clip(GOAL_IMPORTANCE[s['learning_goal']][CONCEPTS[cid]['difficulty']] +
                          CONCEPTS[cid]['importance']*0.15, 0, 1))
            u_total = wm*u_m2 + wt*u_t2 + wp*u_p2 + wg*u_g2
            sens_rows.append({'Scenario': label, 'Concept': CONCEPTS[cid]['name'][:18],
                               'Utility': round(u_total, 3)})

    df_sens = pd.DataFrame(sens_rows)
    fig_s = px.bar(df_sens, x='Concept', y='Utility', color='Scenario',
                   barmode='group', height=350,
                   title='PathWise AI — Sensitivity Analysis: How Top Recommendation Changes with Weights')
    fig_s.update_layout(template='plotly_white', xaxis_tickangle=-30)
    st.plotly_chart(fig_s, use_container_width=True)

# ═══════════════════════════════════════════════════════════════════
# PAGE 5 — RL POLICY
# ═══════════════════════════════════════════════════════════════════

elif page == "🤖 RL Policy":
    st.title("🤖 Reinforcement Learning Policy")

    tab1, tab2, tab3 = st.tabs(["📈 Reward Curve", "📉 Convergence", "🔥 Q-Heatmap"])

    with tab1:
        rewards  = history.get('episode_rewards', [])
        if rewards:
            df_r   = pd.DataFrame({'Episode': range(len(rewards)), 'Reward': rewards})
            df_r['Smoothed'] = df_r['Reward'].rolling(20, min_periods=1).mean()
            fig = go.Figure()
            fig.add_trace(go.Scatter(x=df_r['Episode'], y=df_r['Reward'],
                                     name='Raw', opacity=0.35, line=dict(color='lightcoral')))
            fig.add_trace(go.Scatter(x=df_r['Episode'], y=df_r['Smoothed'],
                                     name='Smoothed (w=20)', line=dict(color='crimson', width=2.5)))
            conv = history.get('converged_at')
            if conv:
                fig.add_vline(x=conv, line_dash='dash', line_color='navy',
                              annotation_text=f'Converged @ ep {conv}')
            fig.update_layout(title='PathWise AI — Cumulative Reward Curve (500 Episodes)',
                              xaxis_title='Episode', yaxis_title='Episode Reward',
                              height=450, template='plotly_white')
            st.plotly_chart(fig, use_container_width=True)
            st.caption(f"Final reward: **{rewards[-1]:.3f}** | Trend: **{'⬆ Upward' if rewards[-1] > rewards[0] else '⬇ Downward'}**")
        else:
            st.info("Run training first.")

    with tab2:
        dq = history.get('episode_delta_q', [])
        if dq:
            df_dq = pd.DataFrame({'Episode': range(len(dq)), 'DeltaQ': dq})
            df_dq['Smoothed'] = df_dq['DeltaQ'].rolling(20, min_periods=1).mean()
            fig2 = go.Figure()
            fig2.add_trace(go.Scatter(x=df_dq['Episode'], y=df_dq['DeltaQ'],
                                      name='Raw ΔQ', opacity=0.3, line=dict(color='lightblue')))
            fig2.add_trace(go.Scatter(x=df_dq['Episode'], y=df_dq['Smoothed'],
                                      name='Smoothed', line=dict(color='steelblue', width=2.5)))
            fig2.add_hline(y=0.001, line_dash='dot', line_color='red',
                           annotation_text='Convergence threshold')
            fig2.update_layout(title='PathWise AI — Q-Table ΔQ Convergence',
                               xaxis_title='Episode', yaxis_title='Mean |ΔQ|',
                               yaxis_type='log', height=450, template='plotly_white')
            st.plotly_chart(fig2, use_container_width=True)
        else:
            st.info("No convergence data. Run training first.")

    with tab3:
        st.subheader("Q-Value Heatmap (top states × all actions)")
        if q_table:
            state_keys = list(q_table.keys())[:12]
            matrix     = np.zeros((len(state_keys), N_CONCEPTS))
            for r, sk in enumerate(state_keys):
                for c, cid in enumerate(CONCEPT_IDS):
                    matrix[r, c] = q_table[sk].get(cid, 0.0) if sk in q_table else 0.0

            fig3 = go.Figure(go.Heatmap(
                z=matrix,
                x=[f"{cid}" for cid in CONCEPT_IDS],
                y=[f"State {i+1}" for i in range(len(state_keys))],
                colorscale='RdYlGn',
                colorbar=dict(title='Q-value'),
                text=[[f"{v:.3f}" for v in row] for row in matrix],
                texttemplate='%{text}',
                textfont=dict(size=8),
            ))
            fig3.update_layout(
                title='PathWise AI — Q-Value Heatmap',
                height=500, template='plotly_white',
                xaxis_title='Concept', yaxis_title='State',
            )
            st.plotly_chart(fig3, use_container_width=True)
        else:
            st.info("No Q-table loaded.")

    st.divider()
    st.subheader("ε-Decay History")
    eps_hist = history.get('epsilon_history', [])
    stag_ev  = history.get('stagnation_events', [])
    if eps_hist:
        fig_e = go.Figure()
        fig_e.add_trace(go.Scatter(y=eps_hist[:2000], mode='lines', name='ε',
                                   line=dict(color='steelblue', width=1.2)))
        for ev in stag_ev:
            fig_e.add_vline(x=ev*15, line_color='red', line_dash='dash',
                            annotation_text='Stagnation boost', opacity=0.6)
        fig_e.update_layout(title='ε Decay (with stagnation boosts in red)',
                             xaxis_title='Step', yaxis_title='ε',
                             height=300, template='plotly_white')
        st.plotly_chart(fig_e, use_container_width=True)

# ═══════════════════════════════════════════════════════════════════
# PAGE 6 — ANALYTICS
# ═══════════════════════════════════════════════════════════════════

elif page == "📊 Analytics":
    st.title("📊 Learning Analytics Dashboard")

    # KPI metrics
    c1, c2, c3 = st.columns(3)
    with c1:
        b_le = metrics.get('baseline_le', 0)
        p_le = metrics.get('pathwise_le', 0)
        st.metric("PathWise LE Score",    f"{p_le:.2f}%",
                  delta=f"+{p_le - b_le:.2f}% vs baseline")
    with c2:
        mr = metrics.get('avg_mastery_rate', 0)
        st.metric("Avg Mastery Rate (MR)", f"{mr:.1f}%")
    with c3:
        ss = metrics.get('avg_satisfaction', 0)
        st.metric("Avg Satisfaction (SS)", f"{ss:.4f}")

    st.divider()

    col_l, col_r = st.columns(2)

    with col_l:
        st.subheader("Learning Efficiency: PathWise AI vs Baseline")
        b_le = metrics.get('baseline_le', 2.0)
        p_le = metrics.get('pathwise_le', 3.0)
        fig_le = go.Figure(go.Bar(
            x=['Random Baseline', 'PathWise AI'],
            y=[b_le, p_le],
            marker_color=['#FF6B6B', '#6BCB77'],
            text=[f"{b_le:.2f}%", f"{p_le:.2f}%"],
            textposition='outside',
        ))
        imp = (p_le - b_le) / b_le * 100 if b_le > 0 else 0
        fig_le.update_layout(
            title=f'LE Improvement: +{imp:.1f}% over random policy',
            yaxis_range=[0, max(b_le,p_le)*1.35],
            height=320, template='plotly_white',
        )
        st.plotly_chart(fig_le, use_container_width=True)

    with col_r:
        st.subheader("Mastery Distribution Across Students")
        if students:
            avg_mastery = [np.mean(s['mastery_vector']) for s in students]
            fig_dist = go.Figure(go.Histogram(
                x=avg_mastery, nbinsx=25,
                marker_color='#4D96FF', opacity=0.8,
            ))
            fig_dist.update_layout(
                title='Distribution of Average Student Mastery',
                xaxis_title='Average Mastery Score',
                yaxis_title='Number of Students',
                height=320, template='plotly_white',
            )
            st.plotly_chart(fig_dist, use_container_width=True)

    st.divider()
    st.subheader("Metrics Formulae")
    st.latex(r"LE = \frac{\text{concepts mastered}}{\text{total study hours}} \times 100")
    st.latex(r"MR = \frac{\text{concepts with mastery} \geq 0.70}{15} \times 100")
    st.latex(r"SS = \frac{\sum_{i=1}^{n} U(a_i, s_i)}{n}")
    st.latex(r"U(a,s) = 0.35 \cdot U_{mastery} + 0.25 \cdot U_{time} + 0.20 \cdot U_{pref} + 0.20 \cdot U_{goal}")

    st.divider()
    st.subheader("Concept Difficulty Distribution")
    diff_counts = pd.Series(
        {d: sum(1 for c in CONCEPTS.values() if c['difficulty'] == d) for d in range(1,6)}
    ).reset_index()
    diff_counts.columns = ['Difficulty', 'Count']
    diff_counts['Label'] = diff_counts['Difficulty'].map(
        {1:'Beginner',2:'Elementary',3:'Intermediate',4:'Advanced',5:'Expert'})
    fig_d = px.pie(diff_counts, values='Count', names='Label',
                   title='PathWise AI — Concept Difficulty Distribution',
                   color_discrete_sequence=px.colors.qualitative.Set2)
    st.plotly_chart(fig_d, use_container_width=True)

    st.divider()
    st.caption("PathWise AI v1.0 — 'Learn Smarter. Progress Faster.'")
